
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://derewzbfouurbfixnvac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlcmV3emJmb3V1cmJmaXhudmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDQ1MTcsImV4cCI6MjA2MDkyMDUxN30.wjxSsr8yK8rpSyNPiKzR60v4m4ZL1K-F3Tgocet5STQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
